# Generated by Django 3.2.7 on 2021-10-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211009_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='TodoUsers',
        ),
    ]
